name: Build (Win/Linux/macOS)

on:
  workflow_dispatch:
  push:
    tags: ["v*"]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            python: "3.11"
          - os: ubuntu-latest
            python: "3.11"
          - os: macos-14
            python: "3.11"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pygame pyinstaller

      - name: Build
        run: |
          python tools/build.py --name MATCH --version "${{ github.ref_name }}" --clean

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MATCH-${{ runner.os }}
          path: dist/MATCH
