- name: Build via build_match.py
  shell: bash
  run: |
    python build_match.py --name MATCH --version "${GITHUB_REF_NAME:-$GITHUB_SHA}" --clean

- name: Sanity print
  shell: bash
  run: |
    echo "Built on $RUNNER_OS"
    [ -d dist ] && ls -la dist || echo "no dist"
    [ -d "dist/MATCH" ] && ls -la "dist/MATCH" || echo "no dist/MATCH"

- name: Ensure dist/MATCH exists
  shell: bash
  run: |
    if [ ! -d "dist/MATCH" ]; then
      echo "::error ::dist/MATCH not found. See build logs above."
      exit 1
    fi
