name: Build (Win/Linux/macOS) ➜ commit win/, linux/, mac/ to `builds` branch

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths-ignore:
      - "win/**"
      - "linux/**"
      - "mac/**"

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.channel }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            channel: win
          - os: ubuntu-latest
            channel: linux
          - os: macos-14
            channel: mac
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install pygame pyinstaller
          # Если на Windows указываешь PNG как --icon и хочешь автоконверсию в ICO, добавь:
          # if [ "$RUNNER_OS" = "Windows" ]; then pip install pillow; fi

      - name: Show tree (pre-build)
        shell: bash
        run: |
          pwd
          ls -la
          ls -la assets_common || true

      - name: Build via build_MATCH.py
        shell: bash
        run: |
          python build_MATCH.py --name MATCH --version "${GITHUB_REF_NAME:-$GITHUB_SHA}" --clean

      - name: Sanity print
        shell: bash
        run: |
          echo "Built on $RUNNER_OS"
          [ -d dist ] && ls -la dist || echo "no dist"
          [ -d "dist/MATCH" ] && ls -la "dist/MATCH" || echo "no dist/MATCH"

      - name: Ensure dist/MATCH exists
        shell: bash
        run: |
          if [ ! -d "dist/MATCH" ]; then
            echo "::error ::dist/MATCH not found. See build logs above."
            exit 1
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: MATCH-${{ matrix.channel }}
          path: dist/MATCH
          if-no-files-found: error

  publish-to-builds-branch:
    name: Commit win/, linux/, mac/ to `builds` branch
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (git state)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: _artifacts

      - name: Prepare working tree on `builds` branch
        shell: bash
        run: |
          set -e

          # перейти/создать ветку builds
          if git ls-remote --exit-code --heads origin builds >/dev/null 2>&1; then
            git checkout builds
          else
            git checkout --orphan builds
            git rm -rf . 2>/dev/null || true
          fi

          # очистить и создать целевые корневые папки
          rm -rf win linux mac
          mkdir -p win linux mac

          # разложить артефакты (названия соответствуют job-именам)
          [ -d "_artifacts/MATCH-win" ]   && cp -a _artifacts/MATCH-win/.   win/
          [ -d "_artifacts/MATCH-linux" ] && cp -a _artifacts/MATCH-linux/. linux/
          [ -d "_artifacts/MATCH-mac" ]   && cp -a _artifacts/MATCH-mac/.   mac/

          echo "Root of builds branch:" && ls -la
          echo "win/:   " && ls -la win   || true
          echo "linux/: " && ls -la linux || true
          echo "mac/:   " && ls -la mac   || true

      - name: Commit & push to `builds`
        env:
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: github-actions@github.com
          GIT_COMMITTER_NAME: github-actions
          GIT_COMMITTER_EMAIL: github-actions@github.com
        shell: bash
        run: |
          set -e
          git add win linux mac
          if git diff --cached --quiet; then
            echo "No changes to commit, skipping."
            exit 0
          fi
          git commit -m "ci: update win/, linux/, mac/ ($(date -u +'%Y-%m-%dT%H:%M:%SZ')) [skip ci]"
          git push origin builds
